### ISSUE TITLE
Add Basic Authorization when accessing HTTP cursor

### ISSUE THREAD

**Issue by DenisCarriere** [pinax-network/substreams-sink#18]
- [x] Add Basic Authorization to HTTP cursor

## Reference

- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Authorization

**Comment by chamorin** [comment]
Added in commit: https://github.com/pinax-network/substreams-sink/commit/3b60290f43e9b050151c5ba5e7405192b41997dc ✔️

**Comment by DenisCarriere** [comment]
I'm thinking we should use the same auth method as Substreams authentication (API Key in Header)
