### ISSUE TITLE
Remove `requiredOption`

### ISSUE THREAD

**Issue by DenisCarriere** [pinax-network/substreams-sink#9]
We should remove `requiredOption`, in case the value is provided as `.env`

https://github.com/pinax-network/substreams-sink/blob/main/src/commander.ts#L47-L49

The idea is you don't need to provide any CLI arguments and everything can be set via `.env`

CLI arguments would be additional overrides, but not required

We're already checking if the field is required or not here:
https://github.com/pinax-network/substreams-sink/blob/main/src/config.ts#L46

**Comment by chamorin** [comment]
Done in commit: https://github.com/pinax-network/substreams-sink/commit/9ef575b9aeaf1f10f405d4ca0a2d44ebd88eb666 with changes to use `new Option(...)`
